FROM python:3.12-slim
WORKDIR /spellbook
COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry==2.2.* && poetry config virtualenvs.create false && poetry install --no-root --no-ansi --no-interaction --no-cache
COPY spellbook/ ./spellbook/
CMD ["uvicorn", "spellbook.main:app", "--host", "0.0.0.0", "--port", "8000"]
